### ISSUE TITLE
run.launch  rosbag

### ISSUE THREAD

**Issue by ustccxy** [PengYu-Team/DCL-SLAM#12]
你好，请问run.launch中这几个bag包中是什么内容，以及应该从哪里获取这几个包
![image](https://github.com/PengYu-Team/DCL-SLAM/assets/33254977/ee8a2abb-a8a5-475f-a1da-e306f5da76d8)

**Comment by heisetiantang** [comment]
我认为，这几个应该是自己录制的数据集，你直接吧kitti切成三段应该也可以

**Comment by zhongshp** [comment]
您好！ustccxy～
这几个包是我们自己录制的数据集，暂时不提供呢，你可以替换成其他分成三段的rosbag。
