### ISSUE TITLE
where is distributed_mapper

### ISSUE THREAD

**Issue by Krasjet-Yu** [PengYu-Team/DCL-SLAM#4]
I can't find https://github.com/PengYu-distributed_mapper_catkin.git.
Is this not open source?

**Comment by ArghyaChatterjee** [comment]
Having the same issue. Where is it ?

**Comment by edwinstudy** [comment]
Have the same issue.please open the source. thanks !

**Comment by edwinstudy** [comment]
> Having the same issue. Where is it ? Need it early for my work.
Have you solve this issue ?

**Comment by haiyang2022** [comment]
I have the same issue, how to solve it?

**Comment by Rotoslider** [comment]
Any chance you will fix this? Or is the project dead?

**Comment by liuzherrui** [comment]
I can't find https://github.com/PengYu-distributed_mapper_catkin.git.
Is this not open source?

**Comment by 512938445** [comment]
A fake open source?

**Comment by zhongshp** [comment]
Hi! The distributed_mapper module, fork from https://github.com/lajoiepy/robust_distributed_mapper, are opened at https://github.com/PengYu-Team/distributed_mapper_catkin. It is a modified version of distributed mapper for DCL-SLAM.
