### ISSUE TITLE
头文件缺失

### ISSUE THREAD

**Issue by diamonazreal** [PengYu-Team/DCL-SLAM#6]
请问这个文件在哪里？
dcl_slam/save_distributed_trajectory.h
是否缺少一个.msg文件？
期待您的解答

**Comment by zhongshp** [comment]
最新的commit已经删掉了这个头文件，删除后可以编译的。

**Comment by 512938445** [comment]
这个 distributedMapping.h 里面的 bool saveDistributedTrajectoryService也得删除吧。这样我才能编译成功。这个工程里找不到这个 save_distributed_trajectoryRequest。

**Comment by zhongshp** [comment]
sry，对的。这些相关的东西均已经删除。
