### ISSUE TITLE
process has died

### ISSUE THREAD

**Issue by 512938445** [PengYu-Team/DCL-SLAM#9]
[a/dcl_lio_sam_mapOptmization-7] process has died [pid 65769, exit code -6, cmd /home/wangda/Downloads/cs/devel/lib/dcl_lio_sam/dcl_lio_sam_mapOptmization __name:=dcl_lio_sam_mapOptmization __log:=/home/wangda/.ros/log/2aa2e9f8-f9fd-11ed-b0d7-3182bc68a46f/a-dcl_lio_sam_mapOptmization-7.log].
log file: /home/wangda/.ros/log/2aa2e9f8-f9fd-11ed-b0d7-3182bc68a46f/a-dcl_lio_sam_mapOptmization-7*.log

**Comment by 512938445** [comment]
你好，我按照README.md 一步一步来的。数据包用的是 S3E_Library.bag。run.launch长这样

`<launch>
	<arg name="set_lio_type" default="1"/> 
	<param name="/number_of_robots" value="3"/>
	<arg name="set_respawn_value" default="false"/>  

	
	<node pkg="rviz" type="rviz" name="dcl_rviz" args="-d $(find dcl_slam)/config/dcl_rviz.rviz" />
	<node pkg="dcl_slam" type="dcl_slam_loopVisualizationNode" name="dcl_slam_loopVisualizationNode" output="screen" />

	
  	<include file="$(find dcl_slam)/launch/single_ugv.launch">
    	<arg name="robotPrefix" value="a"/>
		<arg name="respawnValue" value="$(arg set_respawn_value)"/>
		<arg name="lioType" value="$(arg set_lio_type)"/>
  	</include>

	<include file="$(find dcl_slam)/launch/single_ugv.launch">
    	<arg name="robotPrefix" value="b"/>
		<arg name="respawnValue" value="$(arg set_respawn_value)"/>
		<arg name="lioType" value="$(arg set_lio_type)"/>
  	</include>

	<include file="$(find dcl_slam)/launch/single_ugv.launch">
    	<arg name="robotPrefix" value="c"/>
		<arg name="respawnValue" value="$(arg set_respawn_value)"/>
		<arg name="lioType" value="$(arg set_lio_type)"/>
  	</include>

	
	
	
	
	
	
	<arg name="SYSU_bag" value="/home/wangda/Downloads/S3E_Library.bag"/>
	
	
	

	
	
	
	

	<remap from="/Alpha/velodyne_points" to="/a/velodyne_points"/>
	<remap from="/Bob/velodyne_points" to="/b/velodyne_points"/>
	<remap from="/Carol/velodyne_points" to="/c/velodyne_points"/>
	<remap from="/Alpha/imu/data" to="/a/imu/data"/>
	<remap from="/Bob/imu/data" to="/b/imu/data"/>
	<remap from="/Carol/imu/data" to="/c/imu/data"/>

	<node name="player2" pkg="rosbag" type="play" output="screen" args="-r 1 -q -d 2 $(arg SYSU_bag)"/>

	
</launch>
`

前面都正常运行，运行不到一半的时候a和b就报这个错，然后只有c自己接着往前走

**Comment by zhongshp** [comment]
You may need to create a directory for writing files, please check https://github.com/PengYu-Team/distributed_mapper_catkin/blob/5f4ce8ee06f50776577a1305f89345f79db7fe6e/src/pairwise_consistency_maximization/global_map/global_map.cpp#L11.

**Comment by QingSimon** [comment]
> 3q

Have you solve the problem? I come into the same problem, but it does not work by by creating a directory for writing files.

**Comment by heisetiantang** [comment]
这个方式并没有能够解决节点死亡的问题，请教作者在看看，

**Comment by heisetiantang** [comment]
@zhongshp

**Comment by JoyuZheng** [comment]
@INDEX108 请问你解决了吗？

**Comment by lumole** [comment]
> @INDEX108 请问你解决了吗？
请问解决了吗，我现在也是这个问题

**Comment by lumole** [comment]
解决了，我这面的问题是OPENCV的版本过高，版本换成4.3及以下可以正常跑

**Comment by yigegududeren** [comment]
我的解决了，我直接在我的/home/lyb文件夹下创建一个文件dcl_output，这样就可以了，一定注意不是在ros空间，是在ubuntu安装时，自己命名的home文件夹下创建
